### ISSUE TITLE
Use of "inverse" function /// get_sensor_data() missing /// µC blocks

### ISSUE THREAD

**Issue by Eheran1** [rfetick/Kalman#3] opened 2021-09-29 20:33 UTC
```
Kalman.h:183:16: error: 'class BLA::Matrix<2, 2, BLA::Array<2, 2, float> >' has no member named 'Inverse'
  183 |   K = P*(~H)*S.Inverse(&status);
      |              ~~^~~~~~~
```

The BasicLinearAlgebra Github has [this example](https://github.com/tomstewart89/BasicLinearAlgebra/blob/master/examples/HowToUse/HowToUse.ino) and the syntax is "Invert(Matrix)", so maybe a easy fix? I have solved this by changing that section to:

```
  //K = P*(~H)*S.Inverse(&status);
  bool is_nonsingular = Invert(S);
  K = P*(~H)*S;
  if(is_nonsingular){
  //if(!status){
```

Additionally, in the minimal example:
`kalman_minimal:71:9: error: 'get_sensor_data' was not declared in this scope`
Where is this function? Is it like "SIMULATOR_UPDATE()"?

Additionally:
My Feather M0 stops working (needs manual reset into boot loader) when I include this line:
`KALMAN<Nstate,Nobs> K; // your Kalman filter`
Need to test a different µC --> works with Arduino Leonardo (Pro Micro // MEGA32U4)

PS: 
`Any issue or successful test? Your feedback is important for improving this library. See the Contact section at the end of this file or write to the Group!`
The link is broken. It can be found atleast at one more position.

**Comment by FUEL4EP** [comment] 2021-10-20 14:25
I am facing to the same issue. Could you fix it, please? Thanks a lot in advance.

**Comment by rfetick** [comment] 2021-10-20 14:53
Thanks for your feedback,

It seems that BasicLinearAlgebra had not been updated for 4 years, however 3 months ago it passed to version 3 with changes that might not ensure retro-compatibility with previous versions.

The first option for you is to use previous version of BasicLinearAlgebra.

In the meantime I will work on the Kalman library to match the newest version of BasicLinearAlgebra.

Cheers,

Romain

**Comment by FUEL4EP** [comment] 2021-10-20 15:35
Thanks a lot, Romain!

Your Kalman library is a great library. I use it successfully on a ATMega1284P MCU for doing online multiple linear regressions. It is astonishing that this is possible with such a small memory footprint on an Arduino.

**Comment by rfetick** [comment] 2021-10-27 13:25
The issue seems to be solved if you download the (most recent) version `1.1.0` of the Kalman library and the (most recent) version `3.2` of BasicLinearAlgebra. I hope that future versions of BasicLinearAlgebra will also be compatible.

Cheers,

Romain

**Comment by FUEL4EP** [comment] 2021-10-28 12:27
Thanks a lot for your update, Romain!

It works again after downloading the (most recent) version 1.1.0 of the Kalman library and the (most recent) version 3.2 of BasicLinearAlgebra. :-)
Perfect support!

**Comment by rfetick** [comment] 2022-01-04 10:43
No user reported an error after the patch has been released. I close the issue.

**Closed as completed by rfetick** 2022-01-04 10:43 UTC
Labels: bug
